version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/certificates:/certificates
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - AUTH_API_ADDRESS=http://auth-api:8081
      - TODOS_API_ADDRESS=http://todos-api:8082
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - auth-api
      - todos-api
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`anavheoba.name.ng`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  auth-api:
    build:
      context: ./auth-api
      dockerfile: Dockerfile
    environment:
      - AUTH_API_PORT=8081
      - USERS_API_ADDRESS=http://users-api:8083
      - JWT_SECRET=AyKkSjNNkf2xB/JtY98rt8QA6u95kg9qYg7F7TIEHjI=
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - users-api
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`anavheoba.name.ng`) && PathPrefix(`/api/auth`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls.certresolver=myresolver"
      - "traefik.http.middlewares.auth-strip.stripprefix.prefixes=/api/auth"
      - "traefik.http.routers.auth.middlewares=auth-strip"
      - "traefik.http.services.auth.loadbalancer.server.port=8081"

  todos-api:
    build:
      context: ./todos-api
      dockerfile: Dockerfile
    environment:
      - TODO_API_PORT=8082
      - JWT_SECRET=AyKkSjNNkf2xB/JtY98rt8QA6u95kg9qYg7F7TIEHjI=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - redis
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todos.rule=Host(`anavheoba.name.ng`) && PathPrefix(`/api/todos`)"
      - "traefik.http.routers.todos.entrypoints=websecure"
      - "traefik.http.routers.todos.tls.certresolver=myresolver"
      - "traefik.http.middlewares.todos-strip.stripprefix.prefixes=/api/todos"
      - "traefik.http.routers.todos.middlewares=todos-strip"
      - "traefik.http.services.todos.loadbalancer.server.port=8082"

  redis:
    image: redis:alpine
    networks:
      - app-network

  users-api:
    build:
      context: ./users-api
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8083
      - JWT_SECRET=AyKkSjNNkf2xB/JtY98rt8QA6u95kg9qYg7F7TIEHjI=
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411/
      - SPRING_APPLICATION_NAME=users-api
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users.rule=Host(`anavheoba.name.ng`) && PathPrefix(`/api/users`)"
      - "traefik.http.routers.users.entrypoints=websecure"
      - "traefik.http.routers.users.tls.certresolver=myresolver"
      - "traefik.http.middlewares.users-strip.stripprefix.prefixes=/api/users"
      - "traefik.http.routers.users.middlewares=users-strip"
      - "traefik.http.services.users.loadbalancer.server.port=8083"

  log-message-processor:
    build:
      context: ./log-message-processor
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge