[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true
  insecure = true    # Changed to true for testing

[providers.docker]
  watch = true
  exposedByDefault = false    # Removed network constraint

[certificatesResolvers.myresolver.acme]
  email = "wisdomvolt@gmail.com"
  storage = "/certificates/acme.json"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"