[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true
  insecure = false

[providers.docker]
  watch = true
  network = "app-network"
  exposedByDefault = false

[certificatesResolvers.myresolver.acme]
  email = "wisdomvolt@gmail.com"
  storage = "/certificates/acme.json"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"
